config/routes.rb
Qna::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions

  root 'feed#home'

  match '/questions/signin_show/:id', to: 'questions#signin_show', via: 'get', as: :signin_show

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/edit_elder', to: 'users#edit_elder', via: 'get'
  match '/create_elder', to: 'users#create_elder', via: [:post, :patch]

  match '/create_answer', to: 'questions#create_answer', via: [:post, :patch]

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  acts_as_taggable_on :conditions, :topics

  default_scope -> { order('created_at DESC') }
  validates :content, presence: true
      
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy, :signin_show]

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.paginate(:page => params[:page])
    @user = current_user
    @answer = @user && @question.answers.build(user_id: @user.id)
  end

  def signin_show
    redirect_to action: 'show'
  end

  def new
    @question = current_user.questions.build if signed_in?
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success] = "Question Saved!"
      redirect_to @question
    else
      render 'new'
    end
  end

  def create_answer
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:success] = "Answer Saved!"
    end
    redirect_to @answer.question
  end

  private

  def question_params
    params.require(:question).permit(:content, :topic_list, :condition_list)
  end

  def answer_params
    params.require(:answer).permit(:content, :question_id, :user_id)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<%= link_to question_path(question), :class => 'list-group-item'  do %>
  <span class="user-link" z-index=-1 onclick="userLinkClicked(<%= question.user.id.to_s  %>)">
  <%=  question.user.name %>
  </span> asked: <%= question.content %>
  <br> Topics: <%= question.topic_list %>
  <br> Conditions: <%= question.condition_list %>
  <span class="badge"><%= pluralize(question.answers.count, "answer") %></span>
<% end %>

app/views/questions/new.html.erb
<% provide(:title, 'New Question') %>
<h3>Ask a question</h3>

<div class="container">
  <%= form_for(@question, html: {class: 'form-question', role: 'form'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_area :content, rows: '3', class: 'form-control', placeholder: 'Your Question' %>
  <%= f.text_field :topic_list, class: 'form-control', placeholder: 'Topics' %>
  <%= f.text_field :condition_list, class: 'form-control', placeholder: 'Conditions' %>

  <%= f.submit "Done", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/questions/show.html.erb
<% provide(:title, 'Show Question') %>

  <h3> <%= @question.user.name %> asked </h3>
  <p>  <%= @question.content %> </p>

  Topics: <%= @question.topic_list %>
  <br>
  Conditions: <%= @question.condition_list %>

<% if @answers.count > 0 %>
  <h4>Answers</h4>

  <% @answers.each do |answer| %>
    <%= render answer %>
  <% end %>

  <%= will_paginate @answers %>
<% end %>

<p></p>

<% if @user %> <%# only show answer form if signed in %>

  <%= form_for(@answer, url: '/create_answer', html: {class: 'form-question', role: 'form'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_area :content, rows: '3', class: 'form-control', placeholder: 'Your Answer' %>  
  <%= f.hidden_field :question_id, value: @question.id %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit "Done", class: "btn btn-large btn-primary" %>
  <% end %>

<% else %>

<p>
<%= link_to 'Answer This Question', signin_show_path, class: 'btn btn-primary' %>
</p>
<% end %>